### ISSUE TITLE
Typescript as peerDependency

### ISSUE THREAD

**Issue by dglazkoff** [stephenh/ts-proto#1059]
Do you think maybe a `typescript` should be added as a `peerDependency` in the project?

**Comment by stephenh** [comment]
Hi @dglazkoff ; my initial assumption is no, because I've not really seen that done before (or at all?) but I guess maybe you're thinking that the peerDep would specify some minimal version of `tsc` that the code requires?

If so, honestly I'm not even sure what that is at the moment, i.e. I don't think we use any super-new-ish features of tsc, mostly I'm assuming though because we've not had any bug reports of people still on tsc 4.x asking about it.

**Comment by dglazkoff** [comment]
Yes, I meant some minimum required typescript version. It may be useful to know this information)

**Comment by stephenh** [comment]
I think this is a fair ask (to know the minimum tsc version), but I think when/if we discover it, we would probably just include it in the readme, and not as a true `peerDependency`.

If you'd like to help bisect what our minimum version of tsc actually is (or if you're doing it anyway :-D ), that'd be great, otherwise I'll make sure to document it, the next time someone files an issue about what tsc feature we're using, that isn't supported by their version.
