### ISSUE TITLE
Bug in toJSON Function with `removeEnumPrefix=true` and `unrecognizedEnumValue=0` Option Combination

### ISSUE THREAD

**Issue by kanziw** [stephenh/ts-proto#1086]
I encountered a bug in the `toJSON` function generated by ts-proto when using both the `removeEnumPrefix=true` and `unrecognizedEnumValue=0` options. The issue occurs with the following proto definition:

```proto
enum Quality {
  QUALITY_UNSPECIFIED = 0;
  QUALITY_STANDARD = 1;
  QUALITY_HD = 2;
}
```

When these options are applied, the generated `qualityToJSON` function looks like this:

```ts
export function qualityToJSON(object: Quality): string {
  switch (object) {
    case Quality.UNSPECIFIED:
      return "QUALITY_UNSPECIFIED";
    case Quality.STANDARD:
      return "QUALITY_STANDARD";
    case Quality.HD:
      return "QUALITY_HD";
    default:
      return "UNSPECIFIED";
  }
}
```

The problem lies in the `default` case, where the function returns `"UNSPECIFIED"` instead of `"QUALITY_UNSPECIFIED"`. This leads to incorrect JSON serialization for unrecognized enum values. The `default` case should return `"QUALITY_UNSPECIFIED"`.

**Comment by stephenh** [comment]
Hi @kanziw , you're right, that sounds like a bug! 

If you could add a test case, maybe to this test:

https://github.com/stephenh/ts-proto/tree/main/integration/remove-enum-prefix

The bug is *probably* around in here:

https://github.com/stephenh/ts-proto/blob/main/src/enums.ts#L118

If you could submit a PR, that'd be great! Thanks!
