### ISSUE TITLE
Control over behavior for whether to utilize Date for Timestamp fields

### ISSUE THREAD

**Issue by pedelman** [stephenh/ts-proto#127]
Hello! Thanks for putting together this tool. I have been experimenting with trying to get a configuration of ts-proto that I can hook up to https://scalapb.github.io/json.html. 

I was wondering if it would make sense to include a flag to allow timestamps to be marked as string. It seems like per proto3 canonical json mapping, expected type is string. https://developers.google.com/protocol-buffers/docs/proto3#json

Example proto:

```proto
message TimestampMessage {
    // The timestamp
    google.protobuf.Timestamp created_at = 1;
}
```

Generated typescript interface:

```ts
export interface TimestampMessage {
  /**
   *  The timestamp
   */
  createdAt: Date;
}
```

Desired typescript interface (maybe after passing additional flag):

```ts
export interface TimestampMessage {
  /**
   *  The timestamp
   */
  createdAt: string;
}
```

Cheers!

**Comment by stephenh** [comment]
Hey! At least for the JSON side of things, we already support that, i.e. this `createdAt: Date`:

https://github.com/stephenh/ts-proto/blob/master/integration/simple/simple.ts#L25

Is put on the wire as the ISO string:

https://github.com/stephenh/ts-proto/blob/master/integration/simple/simple.ts#L689

So as long as you go through `FooMessage.toJSON`, instead of like a `JSON.stringify(foo)`, things should be fine?

**Comment by stephenh** [comment]
Per previous comment, pretty sure that, at least for JSON interop, this should already work as you're asking for, i.e. `google.protobuf.Timestamp`s are strings on the wire.
