### ISSUE TITLE
base type

### ISSUE THREAD

**Issue by wisepotato** [stephenh/ts-proto#170]
so currently, all types don't have a base class (such as `ProtoMessage` or something), this way, if I would like to have a class that accepts "any proto message" i can do no such thing. Is it posisble to add such a thing?

**Comment by stephenh** [comment]
The way ts-proto models messages, they are "just POJOs", so you should be able to accept `object` and have that basically be good enough. Also, b/c they are POJOs, there aren't any methods that would be common across all messages that would distinguish them.

I.e. it would be something like:

```
interface ProtoMessage {}
```

Which in typescript, structurally matches any object, regardless of whether they `implement ProtoMessage` or not.

I don't really see this jiving with the ts-proto/interface/POJO approach. If you really want the base class experience, that's what the native protobuf JS bindings / protobufjs code does.

**Comment by wisepotato** [comment]
Sorry, so if i understand correclty if there is an interface `IProtoMessage` it wouldnt know the difference between that and `object`?

If so, you could still implement a nominal typing system. 

I also dont fully understand your protobufjs point, it doesn't do that either.

**Comment by wisepotato** [comment]
also, thanks for making this, it's a nice repo :)

**Comment by stephenh** [comment]
>  it wouldnt know the difference between that and object

Right.

> If so, you could still implement a nominal typing system.

Not sure what you mean, i.e. the brand/tagging techniques? If so, technically yes, but imo the primary benefit of ts-proto is precisely that the objects/messages are "just data" so you can easily build them via object literals, object spreads, and the various built-in/idiomatic ways of manipulating data in JS/TS. So I'm not inclined to purposefully restrict/break this by nominally typing messages.

> protobufjs point, it doesn't do that either.

Ah okay, wrong assumption on my part.

**Comment by wisepotato** [comment]
Cool, seems like a valid argument, maybe then I am using the library wrong, one of the things i'm using it for is a serializer/deserializer, and I would like the object being passed to be it to be any of the valid objects. 

Also as for a nominal typing system: 
```
export type Nominal<T, K> = T & { readonly "type" : K }
```
This would make sure that something that is an `XYZMessage` is never the same as `TQVMessage` even if they have the same properties. (as it just adds a readonly type.) Not saying you should add it, but it exists :)

**Comment by wisepotato** [comment]
I wonder how you're doing this in your own type system? I'm using `any` everywhere because of it.

I would love to have something like the protobuf system in c#:
```
  public interface IProtoMessage
  {
    int CalculateSerializedSize();

    byte[] Serialize();

    int Serialize(Span<byte> buffer);

    void Deserialize(ReadOnlySpan<byte> buffer);
  }
```
I dont think i fully understand why this isnt possible.

**Comment by stephenh** [comment]
> I wonder how you're doing this in your own type system? 

I'm not. 

>  I'm using any everywhere because of it.

So far whenever I want to pass protobuf messages around, I just use the real type, i.e. `processFooMessage(fooMessage: FooMessage)`.

I've not had to write any `genericallyProcessMessage(message: AnyMessage)`.

But even if I did, I would write it as `genericallyProcessMessage(message: any)`, because ts-proto messages _are not classes_.

> I dont think i fully understand why this isnt possible.

Again, ts-proto messages are not classes. So they don't have methods like `Serialize` or `CalculateSerializedSize`. There are not any common methods across `FooMessage` and `BarMessage`, so it doesn't make sense for there to be a base class or a marker interface, because there would not be anything in it.

ts-proto messages are not classes, they are just POJOs / object literals, because it's just more natural / idiomatic in TS to work with data that way. You can declare messages as object literals, you can use `...` object spread to combine/munge objects/keys.

I get its not like C#, but this is not C#. :-) If you want messages that are classes, that is what other TS protobuf libraries do. I understand they don't have the base type that you want, but they at least have classes, which would be where you'd start requesting / adding a base type.

**Comment by wisepotato** [comment]
Ah, please do understand i'm not trying to attack your approach though. But after your message i understand that your way of working is just different to what i expected.

Thanks for the explanation, i get your point now. :)
