### ISSUE TITLE
[Feature Request] Add option to prevent "fromJson" and "fromPartial" to set default values

### ISSUE THREAD

**Issue by TomasWeg** [stephenh/ts-proto#204]
We already know that `fromJson` and `fromPartial` methods set a default value when a property is not present or is undefined, like this:

```typescript
if (object.isEnabled !== undefined && object.isEnabled !== null) {
      message.isEnabled = Boolean(object.isEnabled);
    } else {
      message.isEnabled = false;
    }
```

The previous handling can be useful in some scenarios, but look at the following one:
I have an User model that can be used when I want to update an account.
That model contains 3 properties, `name`, `isEnabled` and `email`.
Imagine I only want to update the `name` of the user, so my HTTP request body will look like this:

```json
{
    "name": "Frank"
}
```

That looks great, but when I read the server:

```typescript
const user = User.fromJson(req.body);
```

This will set `isEnabled` to `false` and `email` to `""` because they weren't found in the JSON, and this will cause the account will be disabled, and the email will be created.

**What I suggest:**
Add an option to prevent that from happening, instead of setting a default value such as `false` or an empty string, set it as undefined.

**Comment by stephenh** [comment]
I get your use case, but isn't this fundamentally not possible in proto3? 

When using the binary protocol, if a caller of your API does:

```
const userUpdate = new User();
userUpdate.isEnabled = false;
userUpdate.email = "";
sendToYourApi(userUpdate);
```

proto3 is will purposefully not include `isEnabled = false` and `email = ""` in the wire protocol "as an optimization", with the understanding that the reader (your server) will just fill in the defaults anyway. "So why bother sending them?" is the rationale.

I'd have to go check the spec, but I assume JSON is the same...ah yes, here:

https://developers.google.com/protocol-buffers/docs/proto3#json

"If a value is missing in the JSON-encoded data or if its value is null, it will be interpreted as the appropriate default value when parsed into a protocol buffer. If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space. An implementation may provide options to emit fields with default values in the JSON-encoded output."

So, I get your use case, but I don't think ts-proto can really help you here, this is "just how protobuf works". Notice that I'm using double quotes a lot, b/c I don't necessarily love this either, i.e. it makes partial update APIs a PITA, but it is what it is.

Fwiw I think you need to model your domain with the wrapper values i.e.:

```
message UserUpdate {
  google.prototbuf.StringValue name = 1,
  google.protobuf.BoolValue isEnabled = 2,
}
```

Because these wrapper values are messages, they are allowed to be undefined on `UserUpdate` and won't have default values foisted on them.

It makes your `*.proto` file uglier, but, again, I think that just is a fundamental limitation of protobuf.

**Comment by TomasWeg** [comment]
But I'm not talking about Protobuf. I said I'm using JSON to encode the messages but using the generator to avoid code the models each time I need a client.

**Comment by stephenh** [comment]
> I'm not talking about Protobuf.

I assume you mean you're not using protobuf-the-binary-format but if you're writing `*.proto` files and using ts-proto's to/fromJSON methods, you're using protobuf-the-json-format and that format & semantics is dictated by the protobuf spec.

I.e. by "each time I need a client" you mean "in a different language like Python, C++, etc.", then it's even more important that ts-proto not implement this suggestion, because that's not how the other protobuf JSON implementations will work.
