### ISSUE TITLE
Variable names without underscore in .ts file

### ISSUE THREAD

**Issue by hardikkat24** [stephenh/ts-proto#251]
Here my proto file has underscores.
```
syntax = "proto3";

message constants {
    bool CAN_SEND_ANALYTICS_EVENTS = 1;
    string CLASSROOM_URL_FRAGMENT_FOR_UNATTACHED_TOPICS = 2;
    string DEFAULT_CLASSROOM_URL_FRAGMENT = 3;
    repeated string ALL_CATEGORIES = 4;
    int32 MAX_COMMIT_MESSAGE_LENGTH = 5;
}

```
But in the .ts generated file, there are no underscores.
```
export interface constants {
  CANSENDANALYTICSEVENTS: boolean;
  CLASSROOMURLFRAGMENTFORUNATTACHEDTOPICS: string;
  DEFAULTCLASSROOMURLFRAGMENT: string;
  ALLCATEGORIES: string[];
  MAXCOMMITMESSAGELENGTH: number;
}
```

How is this possible?
Thanks a lot!

**Comment by hardikkat24** [comment]
Thought it was a bug, rather it was a feature. Can be corrected using `--ts_proto_opt=snakeToCamel=false`. Thanks!

**Comment by stephenh** [comment]
Ah great, glad you figured it out. I agree that initial behavior that initial output did look pretty weird, although makes sense once you know about the camelization behavior.

Fwiw I made the camelization a little smarter, in the next release the `CAN_SEND_ANALYTICS_EVENTS` will become `CanSendAnalyticsEvents` instead of `CANSENDANALYTICSEVENTS`.

You can still use `snakeToCamel=false` if you'd like, but just figured having smarter camelization would be a good thing too.

Thanks for the report!
