### ISSUE TITLE
Base instance has no default value for byte fields

### ISSUE THREAD

**Issue by emil-e** [stephenh/ts-proto#272]
Hi, I see that ts-proto does not generated a default value for byte fields for the base instance:

https://github.com/stephenh/ts-proto/blob/1a8951caf8ba35193c4aee878a16bfed591748d0/src/main.ts#L587

This cases `fromPartial` to give you an invalid proto object. It seems intentional given the explicit exclusion of byte fields but I don't understand it. Is there an explanation for this?

**Comment by stephenh** [comment]
Ah yeah, bytes fields recently got some love in #238. It looks like @willclarktech did purposefully punted on `fromPartial` support, I'm not really sure why.

@willclarktech any thoughts on ^?

**Comment by emil-e** [comment]
@stephenh Okay, I now understand the reason why it's not included in the base message by reading the comments on the change but I don't understand why `fromPartial` was not updated accordingly. It seem explicitly left out according to the last comment:
https://github.com/stephenh/ts-proto/pull/238#discussion_r605576647

**Comment by willclarktech** [comment]
Hello, `fromPartial` is structured slightly differently to `fromJSON` and `decode`. I didn't update `fromPartial` because it seemed like it already handled these. See eg https://github.com/stephenh/ts-proto/blob/main/integration/simple/simple.ts#L586-L590

But looking quickly into the code this morning I actually can't work out how this happens. 😕 

@emil-e Do you have a specific proto file which generates a missing value?

**Comment by emil-e** [comment]
@willclarktech @stephenh This seems to have been a big misunderstanding from my side. I was apparently using an older version of ts-proto without realizing. Updating to the latest version fixes this issue. I apologize!

**Comment by willclarktech** [comment]
@stephenh Might be worth looking into this anyway to make sure it's using `Uint8Array`/`Buffer` correctly.
