### ISSUE TITLE
NestJS return types for gRCP methods

### ISSUE THREAD

**Issue by jsbrain** [stephenh/ts-proto#313]
As seen in the NestJS simple example [here](https://github.com/stephenh/ts-proto/blob/86751fcb0e09fc9ac7249d4932bc1b0eb3343164/integration/nestjs-simple/nestjs-project/hero.controller.ts#L19) the return type is sometimes enforced via `!`, e.g.

```ts
async findOneHero(data: HeroById): Promise<Hero> {
  return this.heroes.find(({ id }) => id === data.id)!; // <- here
}
```

but for me this is an anti pattern and I try to never use ! in my codebase. As this is just example, chances are, this isn't the proper way to do it anyway, which leads to my question:

What is the proper way to handle this?

Does gRPC not allow null types to be returned? If it does allow it, couldn't the generated code simply state `Hero | undefined` as return type?

Or would it be correct to throw an gRPC error if no result if found?

I'm pretty new to gRPC so any advice how to handle this properly would be much appreciated!

**Comment by stephenh** [comment]
Hey @jsbrain really late follow up, but I'm pretty sure RPC methods must return a value, but then within that message, you can have optional fields. So typically you see a pattern:

```
service HeroService {
  rpc FindHero(request FindHeroRequest) returns FindHeroResponse {}
}

message FindHeroResponse
  Hero hero = 1;
```

So that then the `FindHeroResponse.hero` can be empty.

Granted, all of the `FooRequest` + `FooResponse` messages get kind of tedious, but that's what allow the "a return value may be null" behavior you're looking for.

Thanks!

**Comment by jsbrain** [comment]
Right, that's what I came up with in the meantime as well. But thanks for the heads up! 😎
