### ISSUE TITLE
Why no namespaces in generated code?

### ISSUE THREAD

**Issue by renkei** [stephenh/ts-proto#352]
I have two (maybe stupid) questions about design decisions. In the generated code I can see that...

**1. Package names are not reflected as namespace**

Can you explain why the the package name is ignored for scoping messages? Instead, I see a line  like
```typescript
export const protobufPackage = "..."
```
that is just a string. What is it for? How can this be compared to generated C++ or C# code, where package names are converted to namespaces?

**2. Nested enums are not merged as namespace into classes / interfaces**

Let's assume:
```proto
syntax = "proto3";

message MyEvent
{
  enum Type
  {
    Info = 0;
    Warning = 1;
    Error = 2;
  }
  
  Type type = 1;
}
```
I would expect `MyEvent.Type`:
```typescript
export interface MyEvent {
  type: MyEvent.Type;
}

export namespace MyEvent {
  export enum Type {
    Info = 0,
    Warning = 1,
    Error = 2,
  }
}
```
but I get `MyEvent_Type`: 
```typescript
export interface MyEvent {
  type: MyEvent_Type;
}

export enum MyEvent_Type {
  Info = 0,
  Warning = 1,
  Error = 2,
}
```
What's the advantage of the non-scoped datatype with the underscore in its name? This name is not defined in the proto file and could be confusing.

**Comment by stephenh** [comment]
I'd had issues in the past with `namespace` being AFAICT basically "soft deprecated" within TypeScript, i.e. it was a pre-ESM modules sort of thing, and outputs like Babel don't support it.

Er, maybe "didn't support it", b/c it looks like babel does now:

https://github.com/babel/babel/commit/0a988143290da1208475aed84c0429591df7d0f8

I'm pretty sure my first attempt at the `fromJson` + `toJson` methods put them in namespaces (instead of the current `const`s, which I think is basically syntax sugar for `namespace`s anyway).

That said, dunno, they still feel slightly unidiomatic, i.e. in JS/TS generally the file is the unit of modularity directly and not a separate/additional notion of namepaces/packages (which in some languages like Java are locked one to one with file names/paths, but in others are not), and at least anecdotally I've not personally seen a lot of `namespace` usage in TS circles.

So, dunno, that is the original rationale. Not against changing, especially for nested types stuff...

Having the `protobufPackage` more directly affect the output would likely be a large/hard change.
