### ISSUE TITLE
Option to convert Enum to Union Type

### ISSUE THREAD

**Issue by doong-jo** [stephenh/ts-proto#379]
Enum Type is a JavaScript that is created as IIFE when generate JS. It is difficult to take Tree Shaking. How about adding options to convert to Union Type?

### as-is

```
export enum MOBILE_OS {
  IOS = 'iOS',
  ANDROID = 'Android'
}
```

when generate js =>
```
export var MOBILE_OS;
(function (MOBILE_OS) {
    MOBILE_OS[MOBILE_OS["IOS"] = 0] = "IOS";
    MOBILE_OS[MOBILE_OS["ANDROID"] = 1] = "ANDROID";
})(MOBILE_OS || (MOBILE_OS = {}));
```

### to-be

```
export const MOBILE_OS = {
  IOS: 'iOS',
  Android: 'Android'
} as const;
type MOBILE_OS = typeof MOBILE_OS[keyof typeof MOBILE_OS]; // 'iOS' | 'Android'
```

when generate js =>
```
export const MOBILE_OS = {
    IOS: 'iOS',
    Android: 'Android'
};
```

**Comment by stephenh** [comment]
Hey @doong-jo sure, I'd be fine with an "enum as const" option; out of curiosity, would just adding the `const` keyword to the enums achieve what you're looking for:

https://www.typescriptlang.org/docs/handbook/enums.html#const-enums

To a certain extent, it seems like it'd be nice to use a native-TypeScript feature (`const` enums) and/or a webpack/rollup plugin of sort of plugin to solve the "TS enum output is not great" instead of hand-coding an "enum-ish" solution specifically in ts-proto

But I'm open to that too. A PR would be great.
