### ISSUE TITLE
Invalid typescript syntax generated for google.protobuf.Struct RPC replies in v1.88.0

### ISSUE THREAD

**Issue by mkmarek** [stephenh/ts-proto#403]
Hi, there seems to be a regression in v1.88.0 when it comes to decoding response data that are `google.protobuf.Struct`.

I made a small repository to replicate the issue: https://github.com/mkmarek/ts-proto-bug

For a service like this:
```
service Service {
    rpc Bar (BarRequest) returns (google.protobuf.Struct);
}
```

there is this kind of typescript code generated:

```typescript
Bar(
      request: BarRequest
    ): Promise<{[key: string]: any} | undefined> {
      const data = BarRequest.encode(request).finish();
      const promise = this.rpc.request(
        
        "pkg.Service",
        "Bar",
        data
      );
      return promise.then(data => {[key: string]: any} | undefined.decode(new Reader(data)));
    }
```

the ` return promise.then(data => {[key: string]: any} | undefined.decode(new Reader(data)));` has invalid syntax.

## Versions used:

libprotoc 3.0.0
ts-proto v1.88.0

**Comment by stephenh** [comment]
Ah hrm, @boukeversteegh given this is related to `google.protobuf.Struct`, wdyt of ^? I can take a look later as well... Thanks for the report @mkmarek !

**Comment by boukeversteegh** [comment]
Oh yes, I had similar issues in other places. The call-site where the TypeName is resolved assumes that it will always get back a ClassName for 'messages' (not primitives). However, since now we have several message types that don't resolve to class-names by default, you get these breaks.

The fix is easy though, the call site should specify `keepValueType`.

I will look tomorrow or wednesday if no-one else would. We probably need a test for this too.

**Comment by boukeversteegh** [comment]
couldn't help to have a quick look.

the problem is here I think, where `responseType()` should preserve the original value type, and not convert it to typescript.

normally, grpc services cannot return primitives (i think?), so the assumption makes sense.

https://github.com/stephenh/ts-proto/blob/c2e6f81c8a41bd249e4f8ee62d0c2792381fdcd4/src/generate-services.ts#L110-L116
