### ISSUE TITLE
Add Support for Empty Message

### ISSUE THREAD

**Issue by jalandis** [stephenh/ts-proto#52]
It's a trivial use case but for consistency we use an empty message for some endpoints.  This works as is but produces a few lint errors.

```message EmptyResponse{}```

```
app/utils/pb.ts:2146:12 - error TS6133: 'object' is declared but its value is never read.

2146   fromJSON(object: any): EmptyResponse {
```

**Comment by stephenh** [comment]
Ah sure, that makes sense. I can work on a fix. Or let me know if you'd like work on a PR, which would be great.

(General steps for the PR would be to add a `message Empty {}` to `integration/simple/simple.proto`, rerun the `update-bins.sh`, rerun `codegen.sh` to see your compile error, and then edit `main.ts` to iterate on a fix.)

There is a weird work around here you can add:

```
//@ts-nocheck
```

As a comment in your proto file, and that will get output in the TS file as a top-level file comment, and essentially turn off type checking (and since this error) for the whole file. I mean, I don't think that is a very good idea, but just saying it's a quick way to unblock. :-)

**Comment by jalandis** [comment]
I took a stab at a basic fix.  Look forward to hearing your feedback.

**Comment by stephenh** [comment]
Ah nice! That was a lot simpler than I thought it was going to be. :-) I didn't know that `_` was blessed by the `tsc` compiler as "ignore that this field is unused".  Thanks for the PR!

I pushed version 1.18.2 with this fix to npm.
