### ISSUE TITLE
The "optional" keyword is not properly converted

### ISSUE THREAD

**Issue by Zamiell** [stephenh/ts-proto#553]
Greetings, and thanks for the excellent tool.

I am using the `ts-proto` tool to convert the [StarCraft 2 protobuf definitions](https://github.com/Blizzard/s2client-proto/blob/master/s2clientprotocol/sc2api.proto) to TypeScript.

However, it does not seem to handle the `optional` keyword correctly.

For example, the following proto code:

```proto
message RequestCreateGame {
  oneof Map {
    LocalMap local_map = 1;                         // Local .SC2Map file
    string battlenet_map_name = 2;                  // Map published to BattleNet
  }

  repeated PlayerSetup player_setup = 3;

  optional bool disable_fog = 4;

  optional uint32 random_seed = 5;                  // Sets the pseudo-random seed for the game.
  optional bool realtime = 6;                       // If set, the game plays in real time.
}
```

Gets converted to this:

```ts
export interface RequestCreateGame {
  Map?:
    | { $case: "localMap"; localMap: LocalMap }
    | { $case: "battlenetMapName"; battlenetMapName: string };
  playerSetup: PlayerSetup[];
  disableFog: boolean;
  /** Sets the pseudo-random seed for the game. */
  randomSeed: number;
  /** If set, the game plays in real time. */
  realtime: boolean;
}
```

Naively, I would expect that the "optional" keyword would inform the tool that it should insert the question mark operator, like this:

```ts
export interface RequestCreateGame {
  Map?:
    | { $case: "localMap"; localMap: LocalMap }
    | { $case: "battlenetMapName"; battlenetMapName: string };
  playerSetup: PlayerSetup[];
  disableFog?: boolean;
  /** Sets the pseudo-random seed for the game. */
  randomSeed?: number;
  /** If set, the game plays in real time. */
  realtime?: boolean;
```

But this does not appear to be happening. Is this a bug in the software?

**Comment by stephenh** [comment]
Hi @Zamiell , apologies for the really late follow up, but yeah `optional` was dropped in proto3 (although recently added back), and so my guess is that the starcraft protos are proto2 syntax ... ah yep, they are.

We have an issue to better support proto2 optionals: #139.

You could try use `useOptionals=all` which is a new parameter that's been added since #139 was opened. Let me know if that works and maybe we can close #139 as "works if you use `useOptionals=all`".

But even though `useOptionals=all`, given proto3 "re-learned" optional, which ts-proto _does_ support, it might be easier to do the proto2 support as well now, I'm not sure...

For now going to close this as a dup of the other one; thanks!
