### ISSUE TITLE
Support proto2 enums w/o a zero value

### ISSUE THREAD

**Issue by jung-kim** [stephenh/ts-proto#663]
portobuf: https://github.com/apache/pulsar/blob/a73e1f3a2d54d626fc1dfe01e55bc1b8ab0ee8f2/pulsar-common/src/main/proto/PulsarApi.proto
command: `protoc --plugin=node_modules/ts-proto/protoc-gen-ts_proto ./src/proto/PulsarApi.proto -I. --ts_proto_out=. --ts_proto_opt=esModuleInterop=true`

Using above command, I'm not sure why the generated marshal code conditionally writes a required value `type` if `type` is 2, which is `CommandConnect` type.   Looking a the protobuf file, I'm not sure why this is as `CommandConnect` type doesn't require nor specify such treatment.  Similarly [generated golang code doesn't have such issue](https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/pulsar_proto/PulsarApi.pb.go#L12101-L12103).

- `BaseCommand.type` is a simple required field.
<img width="492" alt="Screen Shot 2022-08-28 at 4 05 17 PM" src="https://user-images.githubusercontent.com/5281068/187098263-9dc81dca-67d1-4000-9df7-e323071934b6.png">

- incorrectly generated codes were commented out so that I can proceed.
<img width="723" alt="Screen Shot 2022-08-28 at 4 04 20 PM" src="https://user-images.githubusercontent.com/5281068/187098223-1cb54767-229d-48f6-926d-966c52d99d50.png">

**Comment by stephenh** [comment]
Hey @jung-kim ; sorry for the late response, but yeah, I'm pretty sure this issue is due to this line of code:

https://github.com/stephenh/ts-proto/blob/main/src/types.ts#L192

Which was originally written with the proto3 assumption that enums require a value with `0`; and, when it was written, it was simplest to say "if there is not a `0` value enum, use the first one".

However, you're using proto2, which doesn't have this restriction.

It should be possible to change this line in the code to, instead of picking the first value, just return `undefined`, i.e. indicate there is no appropriate default value for this field.

This would be really easy, but then the 2nd step would be to update any callers of `defaultValue` to handle it returning `undefined`.

I won't personally have time to work on this, but if you'd like to work on a PR for this, that'd be great!

**Comment by stephenh** [comment]
(We may actually have an existing issue for this, b/c someone else has brought up the "proto2 enums w/o a zero value" before...for now just re-titling this issue.)

**Comment by stephenh** [comment]
We have `usePrototypeForDefaults` now which supports this.
