### ISSUE TITLE
Feature Request: add option to return promise with outputServices=grpc-js

### ISSUE THREAD

**Issue by TasukuUno** [stephenh/ts-proto#666]
I think what I want is the same as what the author of #614 wrote. I want to generate gRPC client where all methods return promises, not callbacks.

Interfaces will be like

```ts
export interface GreeterClient extends Client {
  /** Sends a greeting */
  sayHello(
    request: HelloRequest,
  ): Promise<HelloReply>;
```

and also the implementations will wrap `makeGenericClientConstructor` like

```ts
class GreeterClientImpl extends makeGenericClientConstructor(GreeterService, "something") implements GreeterClient {
  sayHello(request: HelloRequest) {
    return new Promise<HelloReply>((resolve, reject) => {
       // call super.sayHello()
    })
  }
}
```

This idea was originally a feature of [protoc-gen-ts](https://github.com/thesayyn/protoc-gen-ts) what I used before. I think this feature would make it easier to call methods. 

Is it possible for you to add such an option?

**Comment by stephenh** [comment]
Hi @TasukuUno , ah yeah that makes a lot of sense. I'm actually kinda surprised the grpc-js output uses callbacks, b/c most of the other clients that ts-proto generates (i.e. for grpc-web) do use promises or observables.

@aikoven worked on our initial grpc-js implementation; Daniel, since you're closing to this than I am, would there be any gotchas to just switching over to promises all together?

@TasukuUno I won't personally have time to work on this, but if you wanted to submit a PR, that'd be great.

**Comment by aikoven** [comment]
Yeah, it's not that easy. The original callback signature returns the `ClientUnaryCall` object:
```ts
export interface GreeterClient extends Client {
  /** Sends a greeting */
  sayHello(
    request: HelloRequest,
    callback: (error: ServiceError | null, response: HelloReply) => void
  ): ClientUnaryCall;
```
which provides ways to abort the call, access its header/trailer metadata etc. Also there are streaming methods where you have to use some stream abstraction instead of promises.

This requires careful API design, that's why we built [nice-grpc](https://github.com/deeplay-io/nice-grpc) 🙂

That said, we could implement promises only for unary methods in `ts-proto`, like `protoc-gen-ts` does. Their docs also say that they support accessing call metadata, so we could just do it the same way.

**Comment by TasukuUno** [comment]
@stephenh @aikoven Hi, thank you for your responses!!!

Yes, I tried [nice-grpc](https://github.com/deeplay-io/nice-grpc) after opening this issue and thought it would be better to use nice-grpc than to add promise feature to ts-proto. I think also adding this feature is not matched to the philosophy wrote in  `Non-Goals` section in [README](https://github.com/stephenh/ts-proto/blob/v1.125.0/README.markdown).

I'll close this issue for now! Thank you!
