### ISSUE TITLE
Generator crashes from v1.123.0 version onwards

### ISSUE THREAD

**Issue by 2m** [stephenh/ts-proto#716]
We have quite a large proto codebase and we have been using v1.122.0 for a while now.

When we tried to upgrade, any new version crashes. We are using buf.build and we do not see any meaningful output:

```
Failure: plugin "buf.build/stephenh/plugins/ts-proto:v1.135.0-0" exited with non-zero status 139:
```

How can we debug this?

**Comment by stephenh** [comment]
Hi @2m , I'm not a buf user, so am not sure; maybe there is a `-v` or `--verbose` or `--debug` flag and/or error log output file?

**Comment by 2m** [comment]
Yup, I tried adding `--verbose` and `--debug` and that gave me more information from the `buf` build itself. However it still does not print anything from the ts-proto plugin itself:
```
...
DEBUG   /buf.alpha.registry.v1alpha1.GenerateService/GeneratePlugins    {"duration": "22.558489067s", "http.status_code": 400, "http.path": "/buf.alpha.registry.v1alpha1.GenerateService/GeneratePlugins", "http.url": "https://api.buf.build/buf.alpha.registry.v1alpha1.GenerateService/GeneratePlugins", "http.host": "api.buf.build", "http.method": "POST", "http.user_agent": "connect-go/1.0.0 (go1.19.3)"}
DEBUG   command {"duration": "22.624581629s"}
Failure: plugin "buf.build/stephenh/plugins/ts-proto:v1.135.0-0" exited with non-zero status 139: 
```
Is there `ts-proto` specific configuration that would give more output?

**Comment by stephenh** [comment]
No; can you invoke ts-proto via protoc and see what happens?

Here is the code for our error handling, which is pretty simple/naive:

https://github.com/stephenh/ts-proto/blob/main/src/plugin.ts#L62

Huh, fwiw we have a hard-coded `process.exit(1)`; ah yeah, 139 in node means seg fault.

In v1.123.0, we moved output formatting from prettier to dprint (but with still "looks like prettier" config settings), which is significantly faster and made a huge/noticeable difference on code generation times.

But, dprint is a native Rust library, so my guess is that it is seg faulting on your input and/or machine setup.

I'm using the latest version of dprint-node:

https://github.com/devongovett/dprint-node

So :thinking: not really sure what to try next.

Technically dprint-node might be a few versions behind the core https://dprint.dev/ project, but the last dprint-node release was in August, so shouldn't be that far behind, and scanning the core dprint commits, I don't see anything going by that is like "fix seg faults".

But, I dunno, if I had to just try stuff, I'd probably try making sure dprint-node was using the super-latest dprint.dev stuff, see if that fixes the seg fault, and if not probably approach the dprint devs with the core dump file and see if they recognize what's going on.

Huge disclaimer that I'm admittedly guessing/correlating that "dprint added in v123" is what is causing the seg fault, but given its a native package, and it is otherwise hard to seg fault node in just vanilla JS, dunno, seems like a good theory.
