### ISSUE TITLE
Support proto3 field presence feature

### ISSUE THREAD

**Issue by linarkou** [stephenh/ts-proto#73]
Hi!
Protobuf released new feature https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/field_presence.md that allows `null`s for primitive types. 
So there is no need in wrappers.
What about support this?

Also see the implementation docs at https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/implementing_proto3_presence.md

**Comment by stephenh** [comment]
Wow @linarkou sorry for taking awhile to get back to you, but I'd heard not about this. This seems like a huge deal. proto3 missing `optional` was a _huge_ complaint I had with it...

I'm still reading the impl details, i.e. about the synthetic oneof approach, but, yes, I think its really reasonable for ts-proto to support this "new" :-) `optional`.

**Comment by stephenh** [comment]
@linarkou let me know if you're interesting in hacking on this, would be great to have a PR. Otherwise it's a great feature, so I'll get around to hacking on it at some point.

**Comment by linarkou** [comment]
@stephenh I'm new in typescript, so I think I can't help you, sorry(

**Comment by cliedeman** [comment]
This probably needs protobufjs support. https://github.com/protobufjs/protobuf.js/issues/1406

**Comment by stephenh** [comment]
@cliedeman I could be wrong, but fwiw I don't think so. ts-proto calls the lower-level reader/write APIs in protobuf.js's `Reader`/`Writer` classes but otherwise drives the `encode`/`decode` process itself, and from my initial read of the spec where "field presence is something something oneofs" (...would have to read it again...) I'm ~80% sure just some changes to ts-proto's generated `encode`/`decode` methods could handle this.

**Comment by stephenh** [comment]
@linarkou @cliedeman I've added supported for this in v1.32.0; I haven't updated the readme yet, but you'll have to use the protoc experimental flag mentioned in their docs. Please report any bugs if you try it and find anything wrong. Thanks!
