### ISSUE TITLE
Typescript compilation is very slow when using --ts_proto_opt=oneof=unions

### ISSUE THREAD

**Issue by garydwatson** [stephenh/ts-proto#818]
when I use --ts_proto_opt=oneof=unions on a hello world project I have my tsc compilation time is 36 seconds to build the project...

when I don't use that option, the tsc compilation time is 5 seconds...

admittedly, I'm importing proto files from a project I already have, and there are a lot of dependencies among those types.

Was hoping to get your thoughts as to the disparity...  I was throwing a quick demo together for my team to demonstrate how they could have strong typing in the project, exhaustive type checks, and automatic serialization/de-serialization from those types, but slowing down the typescript compiler so drastically might be a non-starter for us.

**Comment by stephenh** [comment]
Hey @garydwatson , can you try turning off the exact types, `--ts_proto_opt=useExactTypes=false`, and see if that helps? 

Otherwise I don't think our `oneof=unions` setup is that esoteric, and if anything iirc its pretty standard/idiomatic TypeScript, so I don't think there is something weird we're doing specifically w/oneof=unions that should slow things down...

But obviously there must be; dunno, try the `useExactTypes=false` and see what that is like; it's a shot in the dark but would be great if that magically fixed it.

**Comment by garydwatson** [comment]
I think I'm going to close this issue, thankyou so much for your reply...

I did some more experiments (awhile back at this point), and the results were very non-conclusive, and worse I don't think I'm coming back to this work.

thanks again :)
