### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by harsh599** [stephenh/ts-proto#824]
I am trying to call the encode method but getting error on create() method

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/31313683/236588268-4bb49989-9fc3-476b-af59-4a7dbe62f86d.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/31313683/236588299-a8c1439a-f1cb-49d6-ac26-1d2a6127dcf4.png">

**Comment by stephenh** [comment]
If looks like protobufjs is not importing property. Looks like you're running deno, fwiw my assumption is that protobufjs does not work in deno, but I'm not sure.

If it's the `Writer.create()` that is failing, you can try in your own (non-generated) code, just getting the import to work, something like:

```
import * as pbjs from "protobufjs/minimal.js";
const w = pbjs.Writer.create();
```

Or try `import pbjs from "protobufjs/minimal.js"` / etc.

If you can find an import that works in your own code, and/or otherwise verify whether probobuf.js does actually support deno, then we can figure out how to get the codegen output to match that.

**Comment by harsh599** [comment]
Yeah it worked Thankyou very much.
