### ISSUE TITLE
required fields

### ISSUE THREAD

**Issue by MiranKazaryan** [stephenh/ts-proto#898]
Protobuf strips fields, with the required flag if they are equal to the default initialization value

Those if int = 0, then there will be no field

Is this my mistake or is proto2 not usable 
I want to send message:
      const packet = {
        type: 0,
        ...
      };
      
My proto file :
syntax = "proto2";

message SomeMessage
{
    required uint32 type = 1;
    .....
}

**Comment by stephenh** [comment]
Yes, you're right, default values are not sent over the wire, but ts-proto's `fromJSON` or `decode` methods will restore them, so that your application code will still see "type = 1".

Since you're using proto2, you can check the readme for `usePrototypeForDefaults` which can be useful for older protobuf/proto2 programs that relied on the semantics of "was this default value put on the wire yes/no".
