### ISSUE TITLE
Is there an example of how to use the grpc-web implementation? 

### ISSUE THREAD

**Issue by johnlabarge** [stephenh/ts-proto#955]
I'm not exactly sure how to use the code that is generated by this project though I don't run into most of the issues that I was running into with other typescript grpc attempts (the dreaded d.ts problem), I'm having trouble getting my head around how to use the client to transport messages. I did a generation of the GrpcWeb implementation expecting something like a new MyService(host) that I could use. I'm not following how to use this.

**Comment by stephenh** [comment]
Hi @johnlabarge , yeah, per the disclaimer in the readme, ts-proto is more of a toolkit to setup protobuf stacks (with a wide variety of frameworks/conventions/etc) instead of a polished out-of-the-box that does just one thing well, which means having great tutorials for every combination/framework/etc is just not something we have.

Per grpc-web, probably the best resource is this integration test:

https://github.com/stephenh/ts-proto/blob/main/integration/grpc-web/client-ts.ts

If you'd like to turn that into a small snippet in the readme, or add a note in the readme that links to that, that would be great/very appreciated! Thanks!
