### ISSUE TITLE
Optionally sort keys in output interface types?

### ISSUE THREAD

**Issue by bgentry** [stephenh/ts-proto#991]
We have some protos with a couple dozen fields in them. The generated TS interface types from this library sort those fields in the exported interface declaration exactly the same way as they're sorted in the `.proto` file, or at least in numeric order by field ID.

That's useful when trying to compare to the underlying .proto messages, but it's not a great devex when trying to actually use the generated interfaces in code because fields are all over the place and not sorted alphabetically. For example if I hover over the type in VS Code it's gonna show me the first few fields in their declared order, whatever those happen to be.

For me personally, I would prefer that these generated interfaces have their fields sorted alphabetically so that they're better displayed in my editor. Does it seem crazy to do that? I took a dive into the repo to see where this might be done and it seems like [this](https://github.com/stephenh/ts-proto/compare/main...bgentry:bg-sort-interface-keys?expand=1) could do the trick (of course as an optional setting, with tests, etc) but I wanted to see if you even thought that was a reasonable idea before proceeding.

**Comment by stephenh** [comment]
Hi @bgentry , I think ideally you could tell your IDE your preference, instead of updating all the codebases you want to read to follow the same preference.

It looks like Webstorm can do this maybe:

https://stackoverflow.com/a/77198579/355031

I haven't tried it, nor haven't looked at vscode.

I'm like 80% leaning towards closing the issue as a won't fix, but as you've found it's such a simple change to sort alpha, that I dunno maybe it's fine...

I think I'll optimistically close this as "hopefully you can get your IDE to do this", but lmk if that doesn't work.

**Comment by bgentry** [comment]
I've searched quite a bit and haven't found anything to do this in VS Code. There are of course eslint options to resort keys alphabetically, but these files have eslint disabled so that's pretty tough to get working (would have to manually hack it with a complex post-generation eslint cli invocation).

I would definitely love to use an `alphabetizeProperties` or similar option 😄
